code --install-extension AlanWalk.markdown-toc
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension DotJoshJohnson.xml
code --install-extension dunstontc.viml
code --install-extension eamodio.gitlens
code --install-extension file-icons.file-icons
code --install-extension hbenl.vscode-test-explorer
code --install-extension icrawl.discord-vscode
code --install-extension jpotterm.simple-vim
code --install-extension JScearcy.rust-doc-viewer
code --install-extension matklad.rust-analyzer
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.test-adapter-converter
code --install-extension oderwat.indent-rainbow
code --install-extension panicbit.cargo
code --install-extension serayuzgur.crates
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension Swellaby.vscode-rust-test-adapter
code --install-extension tamasfe.even-better-toml
code --install-extension thedavej.night-owl-black
code --install-extension timonwong.shellcheck
code --install-extension vadimcn.vscode-lldb
code --install-extension Zerotaskx.rust-extension-pack
